from google.cloud import firestore
from google.cloud.firestore_v1.base_query import FieldFilter
from src.config import config

db = firestore.Client(project=config.GCP_PROJECT_ID, database=config.FIRESTORE_DATABASE)


# --- Screen Registry ---

def create_screen(screen_data: dict) -> str:
    """Create a new screen document. Returns screen_id."""
    doc_ref = db.collection("screens").document(screen_data["screen_id"])
    doc_ref.set(screen_data)
    return screen_data["screen_id"]



def get_screen(screen_id: str) -> dict | None:
    """Get a screen by ID."""
    doc = db.collection("screens").document(screen_id).get()
    return doc.to_dict() if doc.exists else None


def update_screen(screen_id: str, updates: dict) -> None:
    """Update fields on a screen document."""
    db.collection("screens").document(screen_id).update(updates)


def get_all_screens() -> list[dict]:
    """Get all screen documents. Used by Orchestrator to build full picture."""
    docs = db.collection("screens").stream()
    return [doc.to_dict() for doc in docs]


# --- Action Tracker ---

def create_action(action_data: dict) -> str:
    """Create a new action document. Returns action_id."""
    doc_ref = db.collection("actions").document(action_data["action_id"])
    doc_ref.set(action_data)
    return action_data["action_id"]


def create_actions_batch(actions: list[dict]) -> int:
    """Create multiple actions in a batch. Returns count created."""
    batch = db.batch()
    for action_data in actions:
        doc_ref = db.collection("actions").document(action_data["action_id"])
        batch.set(doc_ref, action_data)
    batch.commit()
    return len(actions)


def get_pending_actions(screen_id: str) -> list[dict]:
    """Get all pending actions for a screen."""
    docs = (
        db.collection("actions")
        .where(filter=FieldFilter("screen_id", "==", screen_id))
        .where(filter=FieldFilter("status", "==", "pending"))
        .stream()
    )
    return [doc.to_dict() for doc in docs]


def get_actions_by_screen(screen_id: str) -> list[dict]:
    """Get ALL actions for a screen (any status). Used by Orchestrator for full picture."""
    docs = (
        db.collection("actions")
        .where(filter=FieldFilter("screen_id", "==", screen_id))
        .stream()
    )
    return [doc.to_dict() for doc in docs]


def mark_actions_skipped(action_ids: list[str]) -> int:
    """Bulk-skip actions the Orchestrator deems low value. Returns count skipped."""
    if not action_ids:
        return 0
    batch = db.batch()
    screen_ids = set()
    for action_id in action_ids:
        doc_ref = db.collection("actions").document(action_id)
        batch.update(doc_ref, {"status": "skipped"})
        # Collect parent screen_ids to refresh summaries
        doc = doc_ref.get()
        if doc.exists:
            sid = doc.to_dict().get("screen_id")
            if sid:
                screen_ids.add(sid)
    batch.commit()
    for sid in screen_ids:
        _refresh_screen_summary(sid)
    return len(action_ids)


def get_action(action_id: str) -> dict | None:
    """Get a single action by ID. Used by replay navigation."""
    doc = db.collection("actions").document(action_id).get()
    return doc.to_dict() if doc.exists else None


def update_action_fill_value(action_id: str, fill_value: str) -> None:
    """Persist the fill_value generated by Data Provider."""
    db.collection("actions").document(action_id).update({"fill_value": fill_value})


def update_action_status(
    action_id: str,
    status: str,
    outcome: dict | None = None,
    error: str | None = None,
    executed_at: str | None = None,
) -> None:
    """Update an action's status and optionally its outcome, error, and executed_at.

    Also refreshes the parent screen's actions_summary so the
    Orchestrator always sees up-to-date counts.
    """
    updates = {"status": status}
    if outcome:
        updates["actual_outcome"] = outcome
    if error is not None:
        updates["error"] = error
    if executed_at is not None:
        updates["executed_at"] = executed_at
    db.collection("actions").document(action_id).update(updates)

    # Refresh parent screen's actions_summary
    action_doc = db.collection("actions").document(action_id).get()
    if action_doc.exists:
        screen_id = action_doc.to_dict().get("screen_id")
        if screen_id:
            _refresh_screen_summary(screen_id)


def _refresh_screen_summary(screen_id: str) -> None:
    """Recount action statuses and update the screen doc's actions_summary."""
    actions = list(
        db.collection("actions")
        .where(filter=FieldFilter("screen_id", "==", screen_id))
        .stream()
    )
    summary = {"total": len(actions), "pending": 0, "completed": 0, "failed": 0, "skipped": 0}
    for a in actions:
        s = a.to_dict().get("status", "pending")
        if s in summary:
            summary[s] += 1
    db.collection("screens").document(screen_id).update({"actions_summary": summary})


# --- Nav Graph ---

def create_nav_edge(edge_data: dict) -> str:
    """Create a navigation edge. Returns edge_id."""
    doc_ref = db.collection("nav_edges").document(edge_data["edge_id"])
    doc_ref.set(edge_data)
    return edge_data["edge_id"]


def get_nav_edges() -> list[dict]:
    """Get all navigation edges (for graph visualization)."""
    docs = db.collection("nav_edges").stream()
    return [doc.to_dict() for doc in docs]


# --- Cleanup ---

def clear_all() -> None:
    """Delete all docs in screens, actions, nav_edges collections.

    Called at the start of each exploration to ensure a clean state.
    """
    for collection_name in ("screens", "actions", "nav_edges"):
        docs = db.collection(collection_name).stream()
        for doc in docs:
            doc.reference.delete()
    print("Firestore cleared (screens, actions, nav_edges)")
